version: '3.8'

services:
  # The Database Service
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: ecostream_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecostream
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: